name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - id: setup-pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: build
      shell: bash
      run: |
        echo "::group::Build"
        pnpm install
        pnpm build-storybook
        echo "::endgroup::"

    - name: upload
      uses: actions/upload-pages-artifact@v1.0.4
      with: 
        path: storybook-static

    - id: deploy
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ github.token }}